/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.6.11, using .NET Server 3.4.0 template (version 0)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
** </auto-generated>
**
** Copyright (c) 2006-2024 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://yourorganisation.org/DemoOpcUa/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Created: 20.03.2024
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using UnifiedAutomation.UaBase;

namespace cleia.DemoOpcUa
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class DataTypes
    {
        /// <summary>
        /// The identifier for the SlotType DataType.
        /// </summary>
        public const uint SlotType = 3003;

    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class Objects
    {
        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint SlotType_Encoding_DefaultBinary = 5001;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint SlotType_Encoding_DefaultJson = 5003;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint SlotType_Encoding_DefaultXml = 5002;

        /// <summary>
        /// The identifier for the Pus Object.
        /// </summary>
        public const uint Pus = 5006;

        /// <summary>
        /// The identifier for the PuIn Object.
        /// </summary>
        public const uint Pus_PuIn = 5009;

        /// <summary>
        /// The identifier for the http://yourorganisation.org/DemoOpcUa/ Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_DemoOpcUa_ = 5010;

    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class ObjectTypes
    {
    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class Methods
    {
    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the DemoOpcUa Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema = 6001;

        /// <summary>
        /// The identifier for the NamespaceUri Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema_NamespaceUri = 6002;

        /// <summary>
        /// The identifier for the SlotType Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema_SlotType = 6005;

        /// <summary>
        /// The identifier for the DemoOpcUa Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_DemoOpcUa_XmlSchema = 6003;

        /// <summary>
        /// The identifier for the NamespaceUri Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_DemoOpcUa_XmlSchema_NamespaceUri = 6004;

        /// <summary>
        /// The identifier for the SlotType Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_DemoOpcUa_XmlSchema_SlotType = 6006;

        /// <summary>
        /// The identifier for the Dimension Variable.
        /// </summary>
        public const uint SlotVariableType_Dimension = 6020;

        /// <summary>
        /// The identifier for the Location Variable.
        /// </summary>
        public const uint SlotVariableType_Location = 6018;

        /// <summary>
        /// The identifier for the ProductId Variable.
        /// </summary>
        public const uint SlotVariableType_ProductId = 6007;

        /// <summary>
        /// The identifier for the ProductName Variable.
        /// </summary>
        public const uint SlotVariableType_ProductName = 6021;

        /// <summary>
        /// The identifier for the Rotation Variable.
        /// </summary>
        public const uint SlotVariableType_Rotation = 6019;

        /// <summary>
        /// The identifier for the SlotList Object.
        /// </summary>
        public const uint Pus_PuIn_SlotList = 6015;

        /// <summary>
        /// The identifier for the IsNamespaceSubset Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_DemoOpcUa__IsNamespaceSubset = 6008;

        /// <summary>
        /// The identifier for the NamespacePublicationDate Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_DemoOpcUa__NamespacePublicationDate = 6009;

        /// <summary>
        /// The identifier for the NamespaceUri Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_DemoOpcUa__NamespaceUri = 6010;

        /// <summary>
        /// The identifier for the NamespaceVersion Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_DemoOpcUa__NamespaceVersion = 6011;

        /// <summary>
        /// The identifier for the StaticNodeIdTypes Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_DemoOpcUa__StaticNodeIdTypes = 6012;

        /// <summary>
        /// The identifier for the StaticNumericNodeIdRange Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_DemoOpcUa__StaticNumericNodeIdRange = 6013;

        /// <summary>
        /// The identifier for the StaticStringNodeIdPattern Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_DemoOpcUa__StaticStringNodeIdPattern = 6014;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class VariableTypes
    {
        /// <summary>
        /// The identifier for the SlotVariableType VariableType.
        /// </summary>
        public const uint SlotVariableType = 2001;

    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all DataTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class DataTypeIds
    {
        /// <summary>
        /// The identifier for the SlotType DataType.
        /// </summary>
        public static readonly ExpandedNodeId SlotType = new ExpandedNodeId(DataTypes.SlotType, Namespaces.DemoOpcUa);

    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Methods in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class MethodIds
    {
    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class ObjectIds
    {
        /// <summary>
        /// The identifier for the SlotType_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId SlotType_Encoding_DefaultBinary = new ExpandedNodeId(Objects.SlotType_Encoding_DefaultBinary, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the SlotType_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId SlotType_Encoding_DefaultJson = new ExpandedNodeId(Objects.SlotType_Encoding_DefaultJson, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the SlotType_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId SlotType_Encoding_DefaultXml = new ExpandedNodeId(Objects.SlotType_Encoding_DefaultXml, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Pus Object.
        /// </summary>
        public static readonly ExpandedNodeId Pus = new ExpandedNodeId(Objects.Pus, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Pus_PuIn Object.
        /// </summary>
        public static readonly ExpandedNodeId Pus_PuIn = new ExpandedNodeId(Objects.Pus_PuIn, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_DemoOpcUa_ Object.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_DemoOpcUa_ = new ExpandedNodeId(Objects.Namespaces_http___yourorganisation_org_DemoOpcUa_, Namespaces.DemoOpcUa);

    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class ObjectTypeIds
    {
    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all ReferenceTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Variables in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema_NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema_NamespaceUri = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema_NamespaceUri, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema_SlotType Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema_SlotType = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_DemoOpcUa_BinarySchema_SlotType, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_DemoOpcUa_XmlSchema Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_DemoOpcUa_XmlSchema = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_DemoOpcUa_XmlSchema, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_DemoOpcUa_XmlSchema_NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_DemoOpcUa_XmlSchema_NamespaceUri = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_DemoOpcUa_XmlSchema_NamespaceUri, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_DemoOpcUa_XmlSchema_SlotType Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_DemoOpcUa_XmlSchema_SlotType = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_DemoOpcUa_XmlSchema_SlotType, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the SlotVariableType_Dimension Variable.
        /// </summary>
        public static readonly ExpandedNodeId SlotVariableType_Dimension = new ExpandedNodeId(Variables.SlotVariableType_Dimension, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the SlotVariableType_Location Variable.
        /// </summary>
        public static readonly ExpandedNodeId SlotVariableType_Location = new ExpandedNodeId(Variables.SlotVariableType_Location, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the SlotVariableType_ProductId Variable.
        /// </summary>
        public static readonly ExpandedNodeId SlotVariableType_ProductId = new ExpandedNodeId(Variables.SlotVariableType_ProductId, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the SlotVariableType_ProductName Variable.
        /// </summary>
        public static readonly ExpandedNodeId SlotVariableType_ProductName = new ExpandedNodeId(Variables.SlotVariableType_ProductName, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the SlotVariableType_Rotation Variable.
        /// </summary>
        public static readonly ExpandedNodeId SlotVariableType_Rotation = new ExpandedNodeId(Variables.SlotVariableType_Rotation, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Pus_PuIn_SlotList Variable.
        /// </summary>
        public static readonly ExpandedNodeId Pus_PuIn_SlotList = new ExpandedNodeId(Variables.Pus_PuIn_SlotList, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_DemoOpcUa__IsNamespaceSubset Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_DemoOpcUa__IsNamespaceSubset = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_DemoOpcUa__IsNamespaceSubset, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_DemoOpcUa__NamespacePublicationDate Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_DemoOpcUa__NamespacePublicationDate = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_DemoOpcUa__NamespacePublicationDate, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_DemoOpcUa__NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_DemoOpcUa__NamespaceUri = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_DemoOpcUa__NamespaceUri, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_DemoOpcUa__NamespaceVersion Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_DemoOpcUa__NamespaceVersion = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_DemoOpcUa__NamespaceVersion, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_DemoOpcUa__StaticNodeIdTypes Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_DemoOpcUa__StaticNodeIdTypes = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_DemoOpcUa__StaticNodeIdTypes, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_DemoOpcUa__StaticNumericNodeIdRange Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_DemoOpcUa__StaticNumericNodeIdRange = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_DemoOpcUa__StaticNumericNodeIdRange, Namespaces.DemoOpcUa);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_DemoOpcUa__StaticStringNodeIdPattern Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_DemoOpcUa__StaticStringNodeIdPattern = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_DemoOpcUa__StaticStringNodeIdPattern, Namespaces.DemoOpcUa);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all VariableType in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.11")]
    public static partial class VariableTypeIds
    {
        /// <summary>
        /// The identifier for the SlotVariableType VariableType.
        /// </summary>
        public static readonly ExpandedNodeId SlotVariableType = new ExpandedNodeId(VariableTypes.SlotVariableType, Namespaces.DemoOpcUa);

    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the DemoOpcUa component.
        /// </summary>
        public const string DemoOpcUa_XmlSchema = "DemoOpcUa";
        /// <summary>
        /// The BrowseName for the Dimension component.
        /// </summary>
        public const string Dimension = "Dimension";
        /// <summary>
        /// The BrowseName for the Location component.
        /// </summary>
        public const string Location = "Location";
        /// <summary>
        /// The BrowseName for the ProductId component.
        /// </summary>
        public const string ProductId = "ProductId";
        /// <summary>
        /// The BrowseName for the ProductName component.
        /// </summary>
        public const string ProductName = "ProductName";
        /// <summary>
        /// The BrowseName for the PuIn component.
        /// </summary>
        public const string PuIn = "PuIn";
        /// <summary>
        /// The BrowseName for the Pus component.
        /// </summary>
        public const string Pus = "Pus";
        /// <summary>
        /// The BrowseName for the Rotation component.
        /// </summary>
        public const string Rotation = "Rotation";
        /// <summary>
        /// The BrowseName for the SlotList component.
        /// </summary>
        public const string SlotList = "SlotList";
        /// <summary>
        /// The BrowseName for the SlotType component.
        /// </summary>
        public const string SlotType = "SlotType";
        /// <summary>
        /// The BrowseName for the SlotVariableType component.
        /// </summary>
        public const string SlotVariableType = "SlotVariableType";
        /// <summary>
        /// The BrowseName for the http://yourorganisation.org/DemoOpcUa/ component.
        /// </summary>
        public const string http___yourorganisation_org_DemoOpcUa_ = "http://yourorganisation.org/DemoOpcUa/";
    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the Model.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the DemoOpcUa namespace.
        /// </summary>
        public const string DemoOpcUa = "http://yourorganisation.org/DemoOpcUa/";

        /// <summary>
        /// The URI for the DemoOpcUaXsd namespace.
        /// </summary>
        public const string DemoOpcUaXsd = "http://yourorganisation.org/DemoOpcUa/Types.xsd";
    }
    #endregion
}

